import 'package:flutter/material.dart';

class SettingsPage extends StatelessWidget {
  const SettingsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Settings'),
      ),
      body: ListView(
        children: [
          ListTile(
            title: const Text('Privacy Policy'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const PrivacyPolicyPage()),
              );
            },
          ),
          ListTile(
            title: const Text('Terms of Use'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => const TermsOfUsePage()),
              );
            },
          ),
          ListTile(
            title: const Text('Safety & Accuracy'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const SafetyAndAccuracyPage()),
              );
            },
          ),
        ],
      ),
    );
  }
}

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Text('''
1. Data Controller

The controller responsible for data processing is:
[Your Name/Company Name]
[Your Address in Switzerland]

2. Data Sovereignty & Sensitive Data

This app tracks feeding, growth, and health-related information of infants. Under the Swiss Federal Act on Data Protection (nFADP), this is classified as Sensitive Personal Data.

*  Local Storage: All health-related data (feeding times, duration, baby photos) is stored exclusively on your device. We do not have access to this data.

* Backups: If you use iCloud or Google Drive for device backups, your data is encrypted and stored by those providers according to their privacy policies.

3. Data Processing for Subscriptions

To provide the paid features (USD 10/month), we use Apple App Store / Google Play Store.

* Transaction Data: We do not see your credit card details. We receive a "purchase token" and a unique identifier to verify your subscription status.

* Third-Party Processing: We may use service providers (e.g., RevenueCat) to manage subscriptions. These services process anonymized transaction IDs to ensure your access across devices.

4. Zero Tracking & Analytics

* We do not use third-party marketing trackers or analytics that identify you.

* We do not sell or share your data with third parties for advertising.

5. Your Rights

Under the nFADP, you have the right to access, correct, or delete your data. Since all health data is local, you exercise these rights by editing or deleting the information directly within the app or by uninstalling the app.

'''),
      ),
    );
  }
}

class TermsOfUsePage extends StatelessWidget {
  const TermsOfUsePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms of Use'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Text('''
1. Acceptance & Eligibility

By using this app, you agree to these terms. You represent that you are the legal guardian of the child whose data is being tracked.

2. Medical Disclaimer (IMPORTANT)

NOT A MEDICAL DEVICE. This app is a tracking tool for informational purposes only. It does not provide medical advice, diagnosis, or treatment.

* Consult a Professional: Always seek the advice of a pediatrician or qualified health provider for any questions regarding a medical condition or the health/growth of your baby.

* Emergency: Never delay seeking professional medical advice because of information generated by this app. In an emergency, call 144 (Switzerland) or your local emergency number.

3. Subscription & Refunds

* Price: The service is billed at USD 10/month (or equivalent in CHF).

* Management: Subscriptions are managed via your App Store/Google Play account.

* Refunds: As a solo developer, all billing and refunds are handled exclusively by Apple/Google according to their terms.

4. Absolute Data Responsibility

* Local Storage: You acknowledge that this app is "local-first." If you lose your device or delete the app without a system backup (iCloud/Google Drive), your data is permanently lost. We cannot recover it for you.

* Security: You are responsible for securing your device (FaceID/Passcode) to prevent unauthorized access to the sensitive health data stored within the app.

5. Limitation of Liability (Swiss Art. 100 OR)

* To the extent permitted by Swiss law, the Developer is not liable for damages resulting from app errors, data loss, or reliance on the app's statistics.

* Liability Cap: The Developer’s maximum liability for any claim shall not exceed the total amount paid by you for the subscription in the 12 months preceding the claim.

* Exclusion: Liability for gross negligence or unlawful intent remains unaffected as per Art. 100 of the Swiss Code of Obligations.

6. Governing Law & Jurisdiction

These terms are governed by Swiss Law. The exclusive place of jurisdiction for all disputes is Basel, Switzerland.

'''),
      ),
    );
  }
}

class SafetyAndAccuracyPage extends StatelessWidget {
  const SafetyAndAccuracyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Safety & Accuracy'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Text(
            'Manual Data Verification: You must independently verify the accuracy of feeding entries and totals before making care decisions. Technology can fail; your parental judgment is the primary source of care.'),
      ),
    );
  }
}
